### PR TITLE
Improve word guessability.

### PR DESCRIPTION
**Pull request by n1k0**
Refs #8. This patch parses and clean English & French corpuses featuring word usage frequencies and extract dictionaries to be used in game, making selected words more prone to be known and therefore guessed by players. Full length dictionaries are still used to validate user inputs.

/cc @phrawzty

### CODE REVIEW

**Comment by phrawzty** [comment]
The acceptable word list doesn't have:
* thaws
* diety
* daisy

But it did come up with "thats" as an answer, which isn't a word; "that's", with the apostrophe, is a word. Should contractions be in there?

**Comment by n1k0** [comment]
`daisy` was a first name I've now excluded from the `firstnames.txt` blacklist, `thaws` and `diety` were excluded from the range of picked words, so I lowered the threshold for English in https://github.com/n1k0/wordlem/commit/97ac7734aac5954d8496f8f696f3d967f5e29cea

As to `thats`, the misspelling is so common that it's picked from the top 1000 most frequent Google search queries… A solution could be to ensure these picks are members of a more "reasonable" or official dictionary, so we could benefit from the usage frequency metrics provided by Google AND a good reference for what are actual words.

Btw, could you identify a proper exhaustive source for English words (at this point I don't even care about US/UK/etc)?

**Comment by phrawzty** [comment]
> Btw, could you identify a proper exhaustive source for English words (at this point I don't even care about US/UK/etc)?

Unfortunately, English doesn't have a central authority (like French has the Academie, for exmaple). Furthermore, a word that might be super common in, say, Australian English, might be totally unknown in Belizean English—but both would be "proper", contextually.

In short, it's a hard problem, haha. I guess the only thing to do is to just keep refining and eventually get bored with the problem and then give up because hey we're not linguists as it turns out. 😆

**Comment by phrawzty** [comment]
Just got this as an answer, but it's a proper name (i.e. firstnames.txt): [`ellen`](https://www.dictionary.com/browse/ellen)

More names:
- `cuong`
- `chang`
- `evans`

Not English:
- `soins`

I should probably just take a beat and learn how the word lists are being set up so I can propose changes.

**Comment by n1k0** [comment]
Yeah, I should probably write some docs about the process. Here you have to add `ellen` from [`data/firstnames.txt`](https://github.com/n1k0/wordlem/blob/main/data/firstnames.txt). The trickiest part with this file is you must ensure that it doesn't contain first names equivalent to "actual" words (nouns, verbs, adj, etc). For example I had to remove `pierre` (*rock* in French) and `daisy` because even if they're common first names, they're also common nouns, and should therefore be allowed.

**Pull request merged**
